apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-vol-claim
  namespace: crud-app
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual